# Generated by Django 5.2.1 on 2025-06-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='name',
            field=models.CharField(default='Unnamed Item', max_length=250),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservations',
            name='first_name',
            field=models.CharField(default='Unnamed Item', max_length=255),
        ),
        migrations.AddField(
            model_name='reservations',
            name='guest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservations',
            name='last_name',
            field=models.CharField(default='Unnamed Item', max_length=255),
        ),
        migrations.AddField(
            model_name='reservations',
            name='reservation_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='comments',
            field=models.CharField(default='Unnamed', max_length=1000),
        ),
    ]
